### ISSUE TITLE
修改打卡时间

### ISSUE THREAD

**Issue by Linkin-9527** [Bertramoon/DGUT_Auto_Report#3]
你好！
         十分感谢你的开源工作。我想请问一下怎么修改打卡的时间

**Comment by Bertramoon** [comment]
你好，如果需要修改打卡时间，请按照以下步骤：
1、进入到自己仓库下的DGUT_Auto_Report仓库，进入.github/workflows目录，打开目录下的main.yml
2、找到"- cron: '3 8,16,20 * * *'"
3、cron是linux系统下的定时任务，你可以去搜索引擎或论坛上学习cron表达式，或在线生成你所需要的结果，并修改main.yml下对应部分即可。这里我给一个例子，假设你希望在每天的北京时间0时和8时开启打卡任务，那么就将"- cron: '3 8,16,20 * * *'"修改为"- cron: '0 0,16 * * *'"。此处的"0 0,16 * * *"表示在UTC时间每天0时和16时打卡，而北京时间是UTC+8小时，即对应北京时间为8时和0时
4、修改之后记得提交代码到仓库完成修改方可生效


| |
bertramoon
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月8日 ***@***.***> 写道：

你好！
十分感谢你的开源工作。我想请问一下怎么修改打卡的时间

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
